#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2011.1"
URL="http://simpleinvoices.googlecode.com/files/simpleinvoices.${VERSION}.zip"

dl $URL /usr/local/src

