#!/bin/sh -ex

DB_NAME=simpleinvoices
DB_USER=simpleinvoices
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/simpleinvoices

CONF=$WEBROOT/config/config.php

# output SI git log entry of latest commit to build log
git --git-dir $WEBROOT/.git log -1

# set permissions
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown www-data:www-data $CONF

# tweak php.ini
PHPINI=/etc/php/7.0/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 64M|" $PHPINI

# tweak configuration
sed -i "0,\|^database.params.username|s|=.*|= $DB_USER|" $CONF
sed -i "0,\|^database.params.password|s|=.*|= $DB_PASS|" $CONF
sed -i "0,\|^database.params.dbname|s|=.*|= $DB_NAME|" $CONF

sed -i "\|^local.locale|s|=.*|= en_US|" $CONF

sed -i "\|^encryption.default.key|s|=.*|= $(mcookie)|" $CONF
sed -i "\|^nonce.key|s|=.*|= $(mcookie)|" $CONF

sed -i "\|phpSettings.date.timezone|s|=.*|= UTC|" $CONF

# configure apache
a2dissite 000-default
a2ensite simpleinvoices
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

#enable authentication and set default creds
sed -i "s|^authentication.enabled.*|authentication.enabled = true|" $CONF

#we don`t need mysql 1071 error
sed -i "s|\`email\` varchar(255) DEFAULT NULL,|\`email\` varchar(40) DEFAULT NULL,|" $WEBROOT/databases/mysql/Full_Simple_Invoices.sql
sed -i "s|\`name\` varchar(255) NOT NULL,|\`name\` varchar(50) NOT NULL,|" $WEBROOT/databases/mysql/Full_Simple_Invoices.sql

mysql --user=root --password=$MYSQL_PASS $DB_NAME < $WEBROOT/databases/mysql/Full_Simple_Invoices.sql

MD5_PASS=$(echo -n $ADMIN_PASS | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE si_user SET email=\"$ADMIN_MAIL\", password=\"$MD5_PASS\" WHERE id=1;" 

# secure sensitive files
chmod 640 $CONF

# stop services
service mysql stop
service apache2 stop
