#!/bin/bash -e
# regenerate simpleinvoices secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/simpleinvoices/config/config.php
sed -i "\|^encryption.default.key|s|=.*|= $(mcookie)|" $CONF
sed -i "\|^nonce.key|s|=.*|= $(mcookie)|" $CONF

PASSWORD=$(mcookie)
sed -i "0,\|^database.params.password|s|=.*|= $PASSWORD|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=simpleinvoices --pass="$PASSWORD"
