#!/bin/bash -e
# regenerate simpleinvoices secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/simpleinvoices/config/config.ini
sed -i "s|^encryption.default.key.*|encryption.default.key = $(mcookie)|" $CONF
sed -i "s|^nonce.key.*|nonce.key = $(mcookie)|" $CONF

PASSWORD=$(mcookie)
sed -i "0,/params.password/s/params.password.*/params.password = $PASSWORD/" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=simpleinvoices --pass="$PASSWORD"

